### ISSUE TITLE
Hello,I want to know how to ues this code in win10 system?

### ISSUE THREAD

**Issue by Mr-zhao765** [zcablii/SARDet_100K#11]

**Comment by zcablii** [comment]
You may try WSL2 to install a ubuntu subsystem inside Win10, and then run experiments in the ubuntu. Or, you can refer to [this](https://github.com/open-mmlab/mmdetection/issues/2748) solution. MSFA code is totally based on [mmdetection](https://github.com/open-mmlab/mmdetection), therefore you may find tons of solutions on the official mmdetection repo.

**Comment by Mr-zhao765** [comment]
> You may try WSL2 to install a ubuntu subsystem inside Win10, and then run experiments in the ubuntu. Or, you can refer to [this](https://github.com/open-mmlab/mmdetection/issues/2748) solution. MSFA code is totally based on [mmdetection](https://github.com/open-mmlab/mmdetection), therefore you may find tons of solutions on the official mmdetection repo.

Thanks, I will learn mmdetection to find a solution for this
