### ISSUE TITLE
Question Regarding Dataset Annotation

### ISSUE THREAD

**Issue by iAffected** [zcablii/SARDet_100K#13]
I have a question. Typically, the original datasets which typically focus on single-category detection, hence the images only require annotations for the targeted category. If there are other objects present in the image, it’s usually not an issue. However, the SARDet-100K is for multi-category detection, which leads to a potential problem: an original dataset might have annotations for only one type of target in an image, but in reality, there may be other unmarked targets present. For example, a SAR image of an airplane might also contain cars that would not be labeled in the original dataset. This could negatively impact the model training on the SARDet-100K dataset. Have you considered this issue and performed checks on all the images?

**Comment by zcablii** [comment]
Certainly, I appreciate your insightful observation. It's indeed a crucial aspect to address, especially in the context of multi-category detection datasets like SARDet-100K.
It's important to note that datasets focusing on specific categories often optimize image resolution for those specific objects. For instance, in airplane datasets, even if incidental cars are present, they are typically far smaller in terms of pixel size than the typical car objects in the Car datasets.
This situation parallels similar challenges encountered in datasets like DOTA, where variations in Ground Sample Distance (GSD) can lead to instances where certain objects, like cars, may be too small to warrant annotation.
Therefore we mentioned in the main paper that these datasets "have no conflicting object categories".
