### ISSUE TITLE
如何加载预训练模型？

### ISSUE THREAD

**Issue by EEJQX** [zcablii/SARDet_100K#14]
如果我想使用您训练好的模型，从哪里寻找对应模型的代码呢？我貌似没看到模型权值文件对应的实例化代码。

**Comment by zcablii** [comment]
通过配置文件修改中的加载模型权重文件的路径。默认的配置文件放在了[local_configs](https://github.com/zcablii/SARDet_100K/tree/main/MSFA/local_configs)下。更多关于配置文件的说明可参考[mmdet](https://mmdetection.readthedocs.io/en/latest/user_guides/config.html)

**Comment by EEJQX** [comment]
感谢回复！

**Comment by EEJQX** [comment]
KeyError: 'Self_features_model is not in the mmdet::model registry.

**Comment by EEJQX** [comment]
没用过mmdet库，感觉不太好上手哎

**Comment by zcablii** [comment]
> KeyError: 'Self_features_model is not in the mmdet::model registry.

你好像没用最新版本的repo。之前版本的代码里历史遗留问题导致Self_features_model的报错，最新版本的代码已经修复这个问题了。
