### ISSUE TITLE
🔥🔥 PRCV2024 SARDet目标检测竞赛开赛啦 🔥🔥

### ISSUE THREAD

**Issue by zcablii** [zcablii/SARDet_100K#17]
大规模合成孔径雷达图像多类别目标检测竞赛来啦！大赛使用了本工作的SARDet-100K数据集！南开大学[VCIP](https://mmcheng.net/)课题组和CSIG机器视觉专委会、深势科技在PRCV2024联合举办了SARDet目标检测竞赛，本赛道不仅提供实时排行，开箱即用的baseline、工具箱和大规模数据集，还有深势科技官网提供的免费算力券，欢迎广大目标检测爱好者前来华山论剑！

竞赛详情/报名：[PRCV2024 SARDet](https://nb.bohrium.dp.tech/competitions/detail/6816082019?tab=introduce)

**Comment by Blenderama** [comment]
你好，GFL-MSFA的模型权重best_coco_bbox_mAP_epoch_12.pth好像有点问题。我用其他模型在比赛中测试，mAP都是0.5以上，但是GFL的模型的结果与其他差异很大（今天的提交次数用光了，可视化了一下，误检测非常多，每张图片大概几十个物体的样子）
