### ISSUE TITLE
training data set

### ISSUE THREAD

**Issue by paster489** [zcablii/SARDet_100K#19]
Dear Yuxuam,

i want to use your training set for yolo v9 training.

In the annotation train.json file your BBox are not matched to object in image. For example for the image file 0000026.jpg the BBox is:
"images": [
        {
            "file_name": "0000026.jpg",
            "height": 256,
            "width": 256,
            "id": 7622
        }    
    ],

    "annotations": [

        {
            "area": 829.0,
            "iscrowd": 0,
            "image_id": 3086,
            "bbox": [
                642.0,
                11.0,
                65.0,
                39.0
            ],
            "category_id": 0,
            "id": 7622,
            "ignore": 0,
            "segmentation": []
        }
    ],

which is out of image size 256 x 256. i saw that 0000026.jpg is tile of "image_id": 3086 which include additional ~28 tiles. how to merge these tiles to update BBox of 0000026.jpg ? Or maybe you have another method to set correctly BBox of 0000026.jpg ?

thanks you for the help?

**Comment by zcablii** [comment]
I think you may made some misunderstanding on the annotation interpretation. Our annotation is exactly following COCO format. In image 0000026.jpg has an "id" of 7622, which is corresponding to "image_id" in "annotations" section. So, you need to find "annotations" with "image_id": 7622.

**Comment by zcablii** [comment]
It seems there might be some misunderstanding regarding the annotation interpretation. Our annotations strictly follow the COCO format. For instance, the image 0000026.jpg has an "id" of 7622, which corresponds to the "image_id" in the "annotations" section. Therefore, you need to look for annotations where "image_id" is 7622. For more details, u can google "coco dataset annotation interpretation".

**Comment by paster489** [comment]
thank you
