### ISSUE TITLE
关于数据集转yolo格式的问题

### ISSUE THREAD

**Issue by DRAFT-BEER** [zcablii/SARDet_100K#20]
作者您好，我在将您的数据集转yolo格式时遇到了一些问题，yolo数据集标注时会归一化到0-1之间，而在您的数据集中，有几张图像标注时边界框的高宽都大于了图像宽度。请问这是正常的吗？

**Comment by zcablii** [comment]
正常。正如论文中所说，部分图有裁切。坐标超出图的范围的情况不多。但是这种情况并不会太影响模型训练，反而可以看作是一种增强。因为坐标的回归是连续的，让模型通过目标一部分的特征预测出完整位置，是会让模型的学习更鲁棒，这也是为什么我们保留了超出范围的坐标

**Comment by super-song-sir** [comment]
感谢您的回答，我还有一个疑问，我最近在尝试使用yolov8官方的代码来训练数据集，但是代码默认bbox的数值在归一化后的都介于0-1之间，超过0-1范围的图像将会被忽视如图所示
![image](https://github.com/zcablii/SARDet_100K/assets/167293985/1be77d26-fa3f-40c2-b016-4d8b970eddaf)
为了不浪费数据资源，您有哪些处理的建议吗？我目前采取的措施是将归一化后数值大于1的边界框强行变为1。您觉得这种方式可取吗？

**Comment by zcablii** [comment]
个人觉得可以，或者也可以取消忽视的设定。不过这些情况对于整个数据集来说是极少数，估计对性能影响不大。由于我个人没有做实验去验证，以上只是个人的猜测，仅供参考。

**Comment by DRAFT-BEER** [comment]
> 个人觉得可以，或者也可以取消忽视的设定。不过这些情况对于整个数据集来说是极少数，估计对性能影响不大。由于我个人没有做实验去验证，以上只是个人的猜测，仅供参考。

好的非常感谢您的回答
