### ISSUE TITLE
关于预训练的问题

### ISSUE THREAD

**Issue by Iwill-github** [zcablii/SARDet_100K#21]
你好作者，请问一下您使用光学遥感图像进行微调的时候，类别、数量是筛选过的么。据我了解dota和SARDet的类别数量并不相同

**Comment by zcablii** [comment]
没有经过筛选，直接用DOTA/DIOR官方提供的训练集进行的训练。你可以把在光学图像上的训练看做第二阶段的预训练，所以其类别种类和数量不必与SARDet-100K一致。在SARDet-100K上微调时加载整个检测网络权重，但不包括其检测头最后的回归和分类层。

**Comment by Iwill-github** [comment]
> 没有经过筛选，直接用DOTA/DIOR官方提供的训练集进行的训练。你可以把在光学图像上的训练看做第二阶段的预训练，所以其类别种类和数量不必与SARDet-100K一致。在SARDet-100K上微调时加载整个检测网络权重，但不包括其检测头最后的回归和分类层。

了解了，感谢您的回复。
