### ISSUE TITLE
关于训练时长

### ISSUE THREAD

**Issue by ZiMo-Chen** [zcablii/SARDet_100K#22]
你们的模型需要多久的训练时长，单卡A100能否训练，会不会很慢

**Comment by zcablii** [comment]
和模型有关。以VAN_base为例，imagenet预训练单卡估计要10天左右。如果是dota或者SARDet-100K上检测训练，估计两天。具体模型的具体时间可以根据我们提供的log推算。

**Comment by ZiMo-Chen** [comment]
谢谢，你的回复，另外我想问一下 单卡跑 学习率 应该怎么调整会比较合适一些

**Comment by zcablii** [comment]
可尝试根据batch size等比例缩放。比如batch size 16的lr为1e-4， 当使用batch size 8时，可尝试lr 5e-5。

**Comment by ZiMo-Chen** [comment]
> 可尝试根据batch size等比例缩放。比如batch size 16的lr为1e-4， 当使用batch size 8时，可尝试lr 5e-5。

谢谢，这里的batch size是指 多卡总的batch size嘛

**Comment by zcablii** [comment]
是的

**Comment by ZiMo-Chen** [comment]
> 是的

好的 感谢 我等下试试
