### ISSUE TITLE
SAR image inference

### ISSUE THREAD

**Issue by tbxmh** [zcablii/SARDet_100K#28]
I think I have aquestion I would like to ask, which is that I would like to reason about SAR images and detect airplanes or cars in them, but I don't know which models are able to do this? Would you have an answer to this please?

**Comment by zcablii** [comment]
Any of our provided fine-tuned models can perform detection on the SARDet-100K dataset; however, they are unlikely to detect objects outside the training set distribution.

**Comment by tbxmh** [comment]
> Any of our provided fine-tuned models can perform detection on the SARDet-100K dataset; however, they are unlikely to detect objects outside the training set distribution.
I was trying to reason about my own SAR image using the model you guys provided, but it doesn't seem to be working too well; I don't know if it's because of the size of the image, my image's dimensions are 9216*9216; 
I'd like to ask which model and weights are available to detect an aircraft or car
here's my result, running the command:
python . /image_demo.py . /demo/demo.jpg local_configs/SARDet/r50_dota_pretrain/fg_frcnn_dota_pretrain_sar_wavelet_r50_1.py --weights . /work_dirs/fg_frcnn_dota_pretrain_sar_wavelet_r50/best_coco_bbox_mAP_epoch_12.pth --out-dir . /44 --device cpu --show
![20240808191010](https://github.com/user-attachments/assets/b7d35dac-b532-4142-aa29-96a0a54d863d)
