### ISSUE TITLE
Faster RCNN parameters

### ISSUE THREAD

**Issue by MichaelD7911** [zcablii/SARDet_100K#32]
I have a question regarding `MSFA/configs/_base_/models/faster-rcnn_r50_fpn.py`.

The parameters are the **default** of Faster RCNN or **modified** ?

**Comment by zcablii** [comment]
The hyperparameters of Faster R-CNN are set to their default values in the official MMDetection repo. However, the configuration differs from the original paper, as ROI pooling has been replaced with ROI align.
