### ISSUE TITLE
Failure on running training on custom datasets

### ISSUE THREAD

**Issue by CaptainRoby** [zcablii/SARDet_100K#34]
Traceback (most recent call last):
  File "train.py", line 134, in <module>
    main()
  File "train.py", line 130, in main
    runner.train()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1729, in train
    self._train_loop = self.build_train_loop(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1521, in build_train_loop
    loop = LOOPS.build(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 124, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/loops.py", line 44, in __init__
    super().__init__(runner, dataloader)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/base_loop.py", line 26, in __init__
    self.dataloader = runner.build_dataloader(
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1371, in build_dataloader
    dataset = DATASETS.build(dataset_cfg)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/registry.py", line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/registry/build_functions.py", line 124, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/datasets/base_det_dataset.py", line 52, in __init__
    super().__init__(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 248, in __init__
    self.full_init()
  File "/root/miniconda3/lib/python3.8/site-packages/mmdet/datasets/base_det_dataset.py", line 90, in full_init
    self.data_bytes, self.data_address = self._serialize_data()
  File "/root/miniconda3/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 767, in _serialize_data
    data_list = [_serialize(x) for x in self.data_list]
TypeError: 'NoneType' object is not iterable

Above is my traceback of error, when i create an custom dataset in the format of dota datatset, and then i converted its structure and annotations format to coco format, but i still encounter this problem, would it be problem of code itself? and if not, why data_list is None? 
I have debugged it and located the problem on the initialization of basedetdataset class. Does that mean my dataset passed into it has some error? But when i check this code, i saw "self.data_list: List[dict] = []" this statement in the __init__() of basedataset, which is set None to data_list but no arguments was passed to this class initialization method from **args(obj = obj_cls(**args))?
Appreciate for any suggestions or helps! i have struggled on this problem for days [worship]

**Comment by zcablii** [comment]
It looks like your configuration of dataset in the config file is not set properly.  Please check.
If u still suffer from the error, please provide ur config file and ur data folder structure.

**Comment by CaptainRoby** [comment]
/root/miniconda3/lib/python3.8/site-packages/mmdet/datasets/api_wrappers/coco_api.py:22: UserWarning: mmpycocotools is deprecated. Please install official pycocotools by "pip install pycocotools"
  warnings.warn(
loading annotations into memory...
Killed


Above is the result after i add "segmentation" field to my train.json and val.json file. Why the program even "killed" after i add this term? no traceback means no error but the logic of loader exits itself.

Below is my dataset folder's structure:
 |--cocodataset
 |--|---annotations
 |--|     |---train.json
 |--|     |---val.json
 |--|     |---test.json
 |--|---images
 |--|---000001.jpg
 |--|---000002.jpg
 xxx
 
my custom dataset class is familiar with ur in the repo "msfa/datasets/SAR_Det.py", except for classes and palette are changed adjusting for myself need.

**Comment by zcablii** [comment]
maybe [this](https://github.com/open-mmlab/mmdetection/issues/7904) can be helpful

**Comment by CaptainRoby** [comment]
thanks for this "out of memory" problem, but original one was still not solved, can u spot sth. abnormal from my dataset config or folder structure?

**Comment by zcablii** [comment]
may I have a look at ur config file (.py file)?

**Comment by CaptainRoby** [comment]
ok, below is my dataset config file:
# dataset settings
dataset_type = 'SAR_ship_Dataset' 
data_root = '/root/autodl-tmp/cocodataset/'

backend_args = None

train_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', scale=(1024, 1024), keep_ratio=False),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PackDetInputs')
]

test_pipeline = [
    dict(type='LoadImageFromFile', backend_args=backend_args),
    dict(type='Resize', scale=(1024, 1024), keep_ratio=False),
    # If you don't have a gt annotation, delete the pipeline
    # dict(type='LoadAnnotations', with_bbox=True),
    dict(
        type='PackDetInputs',
        meta_keys=('img_id', 'img_path', 'ori_shape', 'img_shape',
                   'scale_factor'))
]

train_dataloader = dict(
    batch_size=16,
    num_workers=8,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    batch_sampler=dict(type='AspectRatioBatchSampler'),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/train.json',
        data_prefix=dict(img='images/'),
        filter_cfg=dict(filter_empty_gt=True, min_size=16),
        pipeline=train_pipeline,
        backend_args=backend_args))

val_dataloader = dict(
    batch_size=4,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/val.json',
        data_prefix=dict(img='images/'),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args))


val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/val.json',
    metric='bbox',
    format_only=False,
    backend_args=backend_args)


test_dataloader = dict(
    batch_size=1,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file='annotations/test.json',
        data_prefix=dict(img='images/'),
        test_mode=True,
        pipeline=test_pipeline,
        backend_args=backend_args))

test_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annfiles/test.json',
    metric='bbox',
    classwise = True,
    format_only=False,
    backend_args=backend_args)

and this is a part of my dataset class definition:
@DATASETS.register_module()
class SAR_ship_Dataset(BaseDetDataset):

    METAINFO = {
        'classes': ('ship', ),
        # palette is a list of color tuples, which is used for visualization.
        'palette':
        [(220, 20, 60)]
    }
    COCOAPI = COCO
    # ann_id is unique in coco dataset.
    ANN_ID_UNIQUE = True

**Comment by zcablii** [comment]
ur config looks fine to me. If ur dataset contains only one single category, u may want to try `dataset_type = 'SAR_Objectness_Dataset'  `
If that still won't work, please check your annotation json file: make sure your "categories" key appear as `"categories": [{"id": 0, "name": "ship"}]`

**Comment by CaptainRoby** [comment]
Problem have been solved by using SAR_Objectness_Dataset instead of a new dataset class inherited from basedetdataset, thank u!
