### ISSUE TITLE
SSDD and HRSID datasets

### ISSUE THREAD

**Issue by GBotong** [zcablii/SARDet_100K#35]
I attempted to reproduce the results you reported in your paper on the SSDD and HRSID datasets, but the original data did not include a validation and test set distinction. The reproduction results fluctuated significantly. Could you provide the dataset splits you used for these two datasets?Thanks.

**Comment by zcablii** [comment]
You can refer to our provided [mapping.json](https://liveuclac-my.sharepoint.com/my?id=%2Fpersonal%2Fzcablii%5Fucl%5Fac%5Fuk%2FDocuments%2Fworks%2FSARDet100K&ga=1)

**Comment by GBotong** [comment]
Thank you very much for your prompt response.
