### ISSUE TITLE
GPU型号咨询

### ISSUE THREAD

**Issue by JourneyOfDream** [zcablii/SARDet_100K#36]
作者您好，我是一个深度学习新手，我看了您的工作后很是敬佩，想要按照您的思路来从头训练一个模型。
我看到您在schedule_1x.py文件中提到` base_batch_size` = (8 GPUs) x (2 samples per GPU)，请问您使用的哪种GPU型号呢，或者您可否推荐一下GPU型号和数量，足以训练这样一个模型？
非常感谢！

**Comment by zcablii** [comment]
我用的是8卡NVIDIA GeForce RTX 3090。
更小显存的GPU我没试过，但是如果受限于计算资源只能使用更小显存的GPU，可以适当减小batch size防止爆显存。GPU数量上，单卡也能跑，只是会慢一些。

**Comment by JourneyOfDream** [comment]
好的好的，万分感谢！
