### ISSUE TITLE
关于预训练

### ISSUE THREAD

**Issue by ocrhei** [zcablii/SARDet_100K#37]
作者您好，最近拜读了您的这篇论文，写的非常棒，但我还有一地困惑。就是在第二个阶段，在遥感数据集上预训练。目前是否有一种风格迁移的方法呢，把烟感数据集，比如dota转换成sar图像风格后再训练呢

**Comment by zcablii** [comment]
这类方式我个人没有去进一步调研，不过听起来也是很可行的。

**Comment by ocrhei** [comment]
> 这类方式我个人没有去进一步调研，不过听起来也是很可行的。

由于您没写训练步骤，因为我有一点点困惑。就是1：请问在用dota数据集预训练的时候，gre或者can等输入增强需要开启么。2：请问用dota数据集预训练的时候，需要将dota数据集转成灰度图吗

**Comment by zcablii** [comment]
预训练的相关配置也提供了喔，config文件以pretrian开头的都是dota预训练的配置，比如[pretrain_mrcnn_cascade_r50_sar_wavelet.py](https://github.com/zcablii/SARDet_100K/blob/main/MSFA/local_configs/SARDet/other_detectors/pretrain_mrcnn_cascade_r50_sar_wavelet.py)。基本的增强用的是默认的，输入是灰度化处理的。

**Comment by mstd-jie** [comment]
> 预训练的相关配置也提供了喔，config文件以pretrian开头的都是dota预训练的配置，比如[pretrain_mrcnn_cascade_r50_sar_wavelet.py](https://github.com/zcablii/SARDet_100K/blob/main/MSFA/local_configs/SARDet/other_detectors/pretrain_mrcnn_cascade_r50_sar_wavelet.py)。基本的增强用的是默认的，输入是灰度化处理的。

非常棒的工作，请问对dota预训练的话，1x和3x对最终模型性能影响大吗

**Comment by zcablii** [comment]
> > 预训练的相关配置也提供了喔，config文件以pretrian开头的都是dota预训练的配置，比如[pretrain_mrcnn_cascade_r50_sar_wavelet.py](https://github.com/zcablii/SARDet_100K/blob/main/MSFA/local_configs/SARDet/other_detectors/pretrain_mrcnn_cascade_r50_sar_wavelet.py)。基本的增强用的是默认的，输入是灰度化处理的。
> 
> 非常棒的工作，请问对dota预训练的话，1x和3x对最终模型性能影响大吗

没试过，不过预计对性能提升不大，因为1x和3x对dota的提升也是有限的
