### ISSUE TITLE
关于检测效果测试

### ISSUE THREAD

**Issue by Aceliulin** [zcablii/SARDet_100K#38]
I have already downloaded your datasets and models weights in Baidu disk. But I don't know how to detect SAR images using your model(with weights). Can you give me a tutorial, if possible?
Thanks!

**Comment by zcablii** [comment]
Our project is primarily built on [MMDetection](https://github.com/open-mmlab/mmdetection). You can refer to the official documentation [here](https://github.com/open-mmlab/mmdetection/tree/main/docs) for any information you need.
