### ISSUE TITLE
KeyError: 'Self_features_model is not in the mmdet::model registry

### ISSUE THREAD

**Issue by ertenggang** [zcablii/SARDet_100K#4]
I have installed the msfa-3.1.0 and downloaded some checkpoints, and I tried to do inference with these models. I got the error when I loaded the checkpoint. 
error message:
KeyError: 'Self_features_model is not in the mmdet::model registry. Please check whether the value of `Self_features_model` is correct or it was registered as expected. More details can be found at https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module'

**Comment by zcablii** [comment]
Apologies for the oversight; that was legacy code we overlooked updating. We've now made a commit to replace 'Self_features_model' with 'MSFA' in the configuration files.
