### ISSUE TITLE
Concerns About Noisy Images in the SARDet100k Dataset

### ISSUE THREAD

**Issue by ssb0621** [zcablii/SARDet_100K#44]
In the SARDet100k training set, the image "0041963.jpg" is annotated with a "ship" object, but the image appears to be a noisy image. Could this image be incorrectly included in the dataset? I have found several other images that seem to be noise-like in the training set. Are such images supposed to be part of the dataset proposed in the paper?

**Comment by zcablii** [comment]
It's true that the SARDet100k training set contains images from various sources, which can result in a wide range of image quality and noise levels. The image "0041963.jpg" you mentioned is indeed characterized by a high level of noise, but it is included intentionally as part of the dataset's diversity.

Despite the noise, the annotation for the "ship" object in "0041963.jpg" is accurate, with the top-left corner coordinates being (271.0, 440.0), a width of 32.0, and a height of 85.0. Upon closer inspection, one can discern a faint outline of the ship, which aligns with the provided annotation.

**Comment by ssb0621** [comment]
Thank you for your response!!
I have one more request.
Could you provide the "mmpretrain code" for MSFA pretraining?

**Comment by zcablii** [comment]
You can directly use [MSFA ](https://github.com/zcablii/SARDet_100K/blob/main/MSFA/msfa/models/backbones/MSFA.py) on mmpretrain by wrapping backbones.
