### ISSUE TITLE
运行

### ISSUE THREAD

**Issue by Fujunxiu123** [zcablii/SARDet_100K#47]
我想之间用你的模型，可以是下载模型里有很多，我应该选哪个，有没有readme。谢谢了

**Comment by zcablii** [comment]
config文件以pretrian开头的都是dota预训练的配置，比如[pretrain_mrcnn_cascade_r50_sar_wavelet.py](https://github.com/zcablii/SARDet_100K/blob/main/MSFA/local_configs/SARDet/other_detectors/pretrain_mrcnn_cascade_r50_sar_wavelet.py). fg_开头的是sardet下游微调的配置文件。下载模型权重的命名是和配置文件对应的
