### ISSUE TITLE
数据集中图片格式

### ISSUE THREAD

**Issue by ZZQ565697818** [zcablii/SARDet_100K#48]
数据集中图片存在jpg，bmp，png等多种格式，我现在使用的模型需要统一图片格式，是否会有影响？能否提供统一图片格式的代码？

**Comment by ZZQ565697818** [comment]
@zcablii 此外数据集标注提供的是coco格式，能否提供像下面的mscoco_category2name
mscoco_category2name = {
    1: 'person',
    2: 'bicycle',
    3: 'car',
    4: 'motorcycle',
    5: 'airplane',
    6: 'bus',
    7: 'train',
    8: 'truck',
    9: 'boat',
    10: 'traffic light',
    11: 'fire hydrant',
    13: 'stop sign',
    14: 'parking meter',
    15: 'bench',
    16: 'bird',
    17: 'cat',
    18: 'dog',
    19: 'horse',
    20: 'sheep',
    21: 'cow',
    22: 'elephant',
    23: 'bear',
    24: 'zebra',
    25: 'giraffe',
    27: 'backpack',
    28: 'umbrella',
    31: 'handbag',
    32: 'tie',
    33: 'suitcase',
    34: 'frisbee',
    35: 'skis',
    36: 'snowboard',
    37: 'sports ball',
    38: 'kite',
    39: 'baseball bat',
    40: 'baseball glove',
    41: 'skateboard',
    42: 'surfboard',
    43: 'tennis racket',
    44: 'bottle',
    46: 'wine glass',
    47: 'cup',
    48: 'fork',
    49: 'knife',
    50: 'spoon',
    51: 'bowl',
    52: 'banana',
    53: 'apple',
    54: 'sandwich',
    55: 'orange',
    56: 'broccoli',
    57: 'carrot',
    58: 'hot dog',
    59: 'pizza',
    60: 'donut',
    61: 'cake',
    62: 'chair',
    63: 'couch',
    64: 'potted plant',
    65: 'bed',
    67: 'dining table',
    70: 'toilet',
    72: 'tv',
    73: 'laptop',
    74: 'mouse',
    75: 'remote',
    76: 'keyboard',
    77: 'cell phone',
    78: 'microwave',
    79: 'oven',
    80: 'toaster',
    81: 'sink',
    82: 'refrigerator',
    84: 'book',
    85: 'clock',
    86: 'vase',
    87: 'scissors',
    88: 'teddy bear',
    89: 'hair drier',
    90: 'toothbrush'
}

**Comment by zcablii** [comment]
虽然是不同的格式，但是存储的图像信息都是8bit的图像。此仓库没有转换代码，不过可以按您的需求自行转换统一格式。

**Comment by zcablii** [comment]
此信息已包含在json标注文件中。

**Comment by ZZQ565697818** [comment]
但光看json文件中的id似乎并不能看出对应的目标物体是什么

**Comment by zcablii** [comment]
SARDet-100K数据集标注格式和COCO一致，也是有“categories”的字段的。

**Comment by ZZQ565697818** [comment]
> SARDet-100K数据集标注格式和COCO一致，也是有“categories”的字段的。

标注中确实有这样的字段，但如RTDETR这样的代码要训练custom data正常是修改代码中像上面提到的mscoco_category2name中的coco数据集的目标与id，要改成自己数据集中的目标物体和对应id，我想问能提供这样的对应，因为sar影像图片光靠肉眼实在无法看出里面有哪些目标物体

**Comment by zcablii** [comment]
“categories”的字段中有这个信息

**Comment by ZZQ565697818** [comment]
> “categories”的字段中有这个信息
我看到的是类似"category_id": 0这样的信息，但这怎么看出是什么物体

**Comment by zcablii** [comment]
和“categories”的字段中的信息对应

**Comment by zcablii** [comment]
json标注文件中有三个字段，分别是“images”，“annotations”和“categories”。我所指的就是这个“categories”字段。

**Comment by ZZQ565697818** [comment]
> json标注文件中有三个字段，分别是“images”，“annotations”和“categories”。我所指的就是这个“categories”字段。

好的，感谢，我看到了，也就是说一共6类物体是吗？
另外还有个问题，我如果将所有图片统一为jpg格式，是否要将json文件中file_name的png和bmp也改为jpg？

**Comment by zcablii** [comment]
是6类。json中的文件名和拓展名都要和你处理后的图片文件一致。

**Comment by ZZQ565697818** [comment]
> 是6类。json中的文件名和拓展名都要和你处理后的图片文件一致。

好的，感谢
