### ISSUE TITLE
Code Application

### ISSUE THREAD

**Issue by 4del-Yousefi** [zcablii/SARDet_100K#5]
I'm not sure about the process or the code to use the models since I'm new to the AI/ML field. Could you provide some guidance? I've prepared the environment and want to apply the trained models to my SAR images.

Thank you,
Adel

**Comment by zcablii** [comment]
This repo is based on [MMDetection](https://github.com/open-mmlab/mmdetection), please refer to [user_guides](https://mmdetection.readthedocs.io/en/latest/user_guides/index.html) for detailed instructions.
