### ISSUE TITLE
can't download configs and weights

### ISSUE THREAD

**Issue by smalltingting** [zcablii/SARDet_100K#6]
I can't find and download configs and weights of Single Stage models and End to End models such as DETR and FCOS. 
Could you please tell me how to solve this problem?Thanks you in advance.

**Comment by zcablii** [comment]
configs and weights are updated

**Comment by paster489** [comment]
how to download weights? thanks

**Comment by zcablii** [comment]
If you can get access to BaiduDisk, here is the [link](https://pan.baidu.com/s/1SuEOl_ImqjoT5Y3pYxZt4w?pwd=c6fo)

**Comment by paster489** [comment]
It is starting a baiduNetdiskHost program and asking for username and
password, i don't know Chinese, I suppose that is what it is asking. I
don't have a password...

**Comment by zcablii** [comment]
No worries, give me a second, I will upload everything to OneDrive

**Comment by zcablii** [comment]
https://liveuclac-my.sharepoint.com/:f:/g/personal/zcablii_ucl_ac_uk/EqaZRwGT9VlAsuw54gqwwkoBxSzVd1cyJldFBMUUFDy0jA?e=EY5H2j

**Comment by paster489** [comment]
thanks a lot

**Comment by paster489** [comment]
additional question => in onedrive for images =>

[image: image.png]

in train there are only 663 images:
[image: image.png]
 and not 94K as mentioned:

[image: image.png]

May I have all the training please?

**Comment by zcablii** [comment]
Make sure you are using this [link](https://liveuclac-my.sharepoint.com/:f:/g/personal/zcablii_ucl_ac_uk/EutczQ-0LB5BmQ1BEguS-PAB8mLXUChRWPVY2Bn5X4-0_w?e=bxPZij) for dataset downloading, as given in the README.

**Comment by paster489** [comment]
ok, thanks,

another question, please => in "Annotations" file, I see only the boundary
box definition, but there is no label id: car, ship, etc. where is the
information please?

**Comment by zcablii** [comment]
category labels are denoted as "category_id".

**Comment by paster489** [comment]
i see, ok, thanks for quick response

the last question in the checkpoint data you sent me to download, I have
weights and config =>

[image: image.png]

but how I know to connect each of them with table?

[image: image.png]

for example for yellow config =>

[image: image.png]
the name of config file is fg_frcnn_IN_sup_sar_r50.py which is not in
checkpoint link you sent me? maybe the name there is different?

**Comment by zcablii** [comment]
yes, some names are different

**Comment by paster489** [comment]
thanks, now additional question, please.

after downloading the weights and config files from onedrive you have sent
me => I ran the next simple code test:


from mmengine.utils import get_git_hash
from mmengine.utils.dl_utils import collect_env as collect_base_env
import mmdet
from mmdet.apis import DetInferencer
config_path_2 = './SAR_Yuxuan_weights/r101_sar.py'
checkpoint_2 = './SAR_Yuxuan_weights/r101_sar_epoch_100.pth'
inferencer_2 = DetInferencer(model=config_path_2, weights=checkpoint_2)


and got the next error => KeyError: 'ImageClassifier is not in the
mmdet::model registry. Please check whether the value of `ImageClassifier`
is correct or it was registered as expected :


Loads checkpoint by local backend from path:
./SAR_Yuxuan_weights/r101_sar_epoch_100.pth
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/SAR_Yuxuan_weights/r101_sar_epoch_100.pth>
---------------------------------------------------------------------------
KeyError Traceback (most recent call last) Input In [28], in <cell line: 7>
() 5 config_path_2 = './SAR_Yuxuan_weights/r101_sar.py
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/SAR_Yuxuan_weights/r101_sar.py>
' 6 checkpoint_2 = './SAR_Yuxuan_weights/r101_sar_epoch_100.pth
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/SAR_Yuxuan_weights/r101_sar_epoch_100.pth>
' ----> 7 inferencer_2 = DetInferencer(model=config_path_2,
weights=checkpoint_2)
File
~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:98
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:98>,
in DetInferencer.__init__(self, model, weights, device, scope, palette,
show_progress) 96
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:96>
self.palette = palette 97
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:97>
init_default_scope(scope) ---> 98
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:98>
super().__init__( 99
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:99>
model=model, weights=weights, device=device, scope=scope) 100
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:100>
self.model = revert_sync_batchnorm(self.model) 101
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py:101>
self.show_progress = show_progress File
~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:180
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:180>,
in BaseInferencer.__init__(self, model, weights, device, scope,
show_progress) 177
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:177>
if device is None: 178
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:178>
device = get_device() --> 180
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:180>
self.model = self._init_model(cfg, weights, device) # type: ignore 181
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:181>
self.pipeline = self._init_pipeline(cfg) 182
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:182>
self.collate_fn = self._init_collate(cfg) File
~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:483
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:483>,
in BaseInferencer._init_model(self, cfg, weights, device) 480
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:480>
if cfg.model.get('pretrained') is not None: 481
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py:481>
del cfg.model.pretrained
...
106
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py:106>
) 107
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py:107>
#
this will include classes, functions, partial functions and more 108
<https://file+.vscode-resource.vscode-cdn.net/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/~/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py:108>
elif callable(obj_type): KeyError: 'ImageClassifier is not in the
mmdet::model registry. Please check whether the value of `ImageClassifier`
is correct or it was registered as expected. More details can be found at
https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module
'
Output is truncated. View as a scrollable element or open in a text editor.
Adjust cell output settings...

Could you advise how to fix it please?

thanks

**Comment by zcablii** [comment]
It is because you load a config and model weight for classification, but use a detection environment(mmdet). You can go to [mmpretrain](https://github.com/open-mmlab/mmpretrain) for classification model verification.

**Comment by paster489** [comment]
I see, my curiosity is to check object detection and not classification.
from the config files which you sent me above which one is for detection?
thanks

**Comment by paster489** [comment]
by the way, I took another config file (hope it is detection) =>

from mmengine.utils import get_git_hash
from mmengine.utils.dl_utils import collect_env as collect_base_env
import mmdet
from mmdet.apis import DetInferencer


def collect_env():
"""Collect the information of the running environments."""
env_info = collect_base_env()
env_info['MMDetection'] = f'{mmdet.__version__}+{get_git_hash()[:7]}'
return env_info

def main():

config_file =
'./mmdetection/SAR_Yuxuan_weights/fg_frcnn_dota_pretrain_sar_wavelet_r50/fg_frcnn_dota_pretrain_sar_wavelet_r50.py'
checkpoint_file =
'./mmdetection/SAR_Yuxuan_weights/fg_frcnn_dota_pretrain_sar_wavelet_r50/best_coco_bbox_mAP_epoch_12.pth'

# Initialize the DetInferencer
inferencer_2 = DetInferencer(model=config_file, weights=checkpoint_file)


if __name__ == '__main__':
main()
#for name, val in collect_env().items():
#print(f'{name}: {val}')





the error is: KeyError: 'Self_features_model is not in the mmdet::model
registry. Please check whether the value of `Self_features_model` is
correct or it was registered as expected

Loads checkpoint by local backend from path:
./mmdetection/SAR_Yuxuan_weights/fg_frcnn_dota_pretrain_sar_wavelet_r50/best_coco_bbox_mAP_epoch_12.pth
Traceback (most recent call last):
  File "/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/test_2.py",
line 23, in <module>
    main()
  File "/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/test_2.py",
line 19, in main
    inferencer_2 = DetInferencer(model=config_file, weights=checkpoint_file)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py",
line 98, in __init__
    super().__init__(
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py",
line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py",
line 483, in _init_model
    model = MODELS.build(cfg.model)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/registry.py",
line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/models/detectors/faster_rcnn.py",
line 20, in __init__
    super().__init__(
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py",
line 34, in __init__
    self.backbone = MODELS.build(backbone)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/registry.py",
line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 100, in build_from_cfg
    raise KeyError(
KeyError: 'Self_features_model is not in the mmdet::model registry. Please
check whether the value of `Self_features_model` is correct or it was
registered as expected. More details can be found at
https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module
'

**Comment by zcablii** [comment]
please use the configs I provided in the repo. The configs with the weight files are a bit out of date because I made some code refactory and renaming.

**Comment by paster489** [comment]
I see thanks..
but i took the config file from your repository and weights from
Onefrove you sent me and still it is not working:

rom mmengine.utils import get_git_hash
from mmengine.utils.dl_utils import collect_env as collect_base_env
import mmdet
from mmdet.apis import DetInferencer


def collect_env():
"""Collect the information of the running environments."""
env_info = collect_base_env()
env_info['MMDetection'] = f'{mmdet.__version__}+{get_git_hash()[:7]}'
return env_info

def main():

config_file =
'./local_configs/SARDet/other_backbones/fg_frcnn_dota_pretrain_sar_r101_wavelet.py'
checkpoint_file =
'./mmdetection/SAR_Yuxuan_weights/fg_frcnn_dota_pretrain_sar_r101_wavelet/best_coco_bbox_mAP_epoch_12.pth'

# Initialize the DetInferencer
inferencer_2 = DetInferencer(model=config_file, weights=checkpoint_file)


if __name__ == '__main__':
main()
#for name, val in collect_env().items():
#print(f'{name}: {val}')




error:  KeyError: 'MSFA is not in the mmdet::model registry. Please check
whether the value of `MSFA` is correct or it was registered as expected.


Loads checkpoint by local backend from path:
./mmdetection/SAR_Yuxuan_weights/fg_frcnn_dota_pretrain_sar_r101_wavelet/best_coco_bbox_mAP_epoch_12.pth
Traceback (most recent call last):
  File "/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/test_2.py",
line 23, in <module>
    main()
  File "/home/paster/Documents/SAR_inference/SARDet_100K/MSFA/test_2.py",
line 19, in main
    inferencer_2 = DetInferencer(model=config_file, weights=checkpoint_file)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/apis/det_inferencer.py",
line 98, in __init__
    super().__init__(
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py",
line 180, in __init__
    self.model = self._init_model(cfg, weights, device)  # type: ignore
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/infer/infer.py",
line 483, in _init_model
    model = MODELS.build(cfg.model)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/registry.py",
line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/models/detectors/faster_rcnn.py",
line 20, in __init__
    super().__init__(
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmdet/models/detectors/two_stage.py",
line 34, in __init__
    self.backbone = MODELS.build(backbone)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/registry.py",
line 570, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 232, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File
"/home/paster/anaconda3/envs/MSFA/lib/python3.8/site-packages/mmengine/registry/build_functions.py",
line 100, in build_from_cfg
    raise KeyError(
KeyError: 'MSFA is not in the mmdet::model registry. Please check whether
the value of `MSFA` is correct or it was registered as expected. More
details can be found at
https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html#import-the-custom-module
'
(base) ***@***.***:~/Documents/SAR_inference/SARDet_100K/MSFA$


thank you very much for help

**Comment by zcablii** [comment]
Your environment is not properly installed.

**Comment by paster489** [comment]
I see... I did exactly according to repo instructions:


# change directory into the project main code
cd MSFA

# create env
conda create -y -n MSFA python=3.8
conda activate MSFA

# install pytorch
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
pytorch-cuda=11.8 -c pytorch -c nvidia
# or
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2
--index-url https://download.pytorch.org/whl/cu118

# install dependencies of openmmlab
pip install -U openmim
mim install "mmengine==0.8.4"
mim install "mmcv==2.0.1"
mim install "mmdet==3.1.0"

# install other dependencies
pip install -r requirements.txt

# install MSFA
pip install -v -e .


The conda list is:

# packages in environment at /home/paster/anaconda3/envs/MSFA:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
addict                    2.4.0                    pypi_0    pypi
aliyun-python-sdk-core    2.15.1                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.2                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.4.1              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
blas                      1.0                         mkl
brotli-python             1.0.9            py38heb0550a_2
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2         py38h06a4308_0
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
comm                      0.2.2                    pypi_0    pypi
configparser              7.0.0                    pypi_0    pypi
contourpy                 1.1.1                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              42.0.5                   pypi_0    pypi
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cycler                    0.12.1                   pypi_0    pypi
debugpy                   1.8.1            py38h17151c0_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
executing                 2.0.1              pyhd8ed1ab_0    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1           py38h06a4308_0
fonttools                 4.51.0                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0
giflib                    5.2.1                h7b6447c_0
gmp                       6.2.1                h295c915_3
gmpy2                     2.1.2            py38heeb90bb_0
gnutls                    3.6.15               he1e5248_0
idna                      3.4              py38h06a4308_0
importlib-metadata        7.1.0              pyha770c72_0    conda-forge
importlib-resources       6.4.0                    pypi_0    pypi
importlib_metadata        7.1.0                hd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h06a4308_3561
ipykernel                 6.14.0           py38h7f3c49e_0    conda-forge
ipython                   8.4.0            py38h578d9bd_0    conda-forge
ipywidgets                8.1.2                    pypi_0    pypi
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.3            py38h06a4308_0
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9e                   h7f8727e_0
jupyter_client            8.6.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2            py38h578d9bd_0    conda-forge
jupyterlab-widgets        3.0.10                   pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
kymatio                   0.3.0                    pypi_0    pypi
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.9.1.3                       0    nvidia
libcurand                 10.3.5.147                    0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libffi                    3.3                  he6710b0_2
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libiconv                  1.16                 h7f8727e_2
libidn2                   2.3.2                h7f8727e_0
libnpp                    11.8.0.86                     0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtasn1                  4.16.0               h27cfd23_0
libtiff                   4.2.0                h2818925_1
libunistring              0.9.10               h27cfd23_0
libwebp                   1.2.2                h55f646e_0
libwebp-base              1.2.2                h7f8727e_0
lz4-c                     1.9.3                h295c915_1
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.1            py38h7f8727e_0
matplotlib                3.7.5                    pypi_0    pypi
matplotlib-inline         0.1.7              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640
mkl-service               2.4.0            py38h7f8727e_0
mkl_fft                   1.3.1            py38hd3c417c_0
mkl_random                1.2.2            py38h51133e4_0
mmcv                      2.0.1                    pypi_0    pypi
mmdet                     3.1.0                    pypi_0    pypi
mmengine                  0.8.4                    pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpmath                    1.3.0            py38h06a4308_0
msfa                      3.1.0                     dev_0    <develop>
ncurses                   6.3                  h7f8727e_2
nest-asyncio              1.6.0              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                hbbd107a_1
networkx                  3.1              py38h06a4308_0
numpy                     1.22.3           py38he7a7128_0
numpy-base                1.22.3           py38hf524024_0
opencv-python             4.9.0.80                 pypi_0    pypi
opendatalab               0.0.10                   pypi_0    pypi
openh264                  2.1.1                h4ff587b_0
openmim                   0.3.9                    pypi_0    pypi
openssl                   1.1.1w               hd590300_0    conda-forge
openxlab                  0.0.38                   pypi_0    pypi
ordered-set               4.1.0                    pypi_0    pypi
oss2                      2.17.0                   pypi_0    pypi
packaging                 24.0               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3                    pypi_0    pypi
parso                     0.8.4              pyhd8ed1ab_0    conda-forge
pexpect                   4.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.0.1            py38h22f2fdc_0
pip                       23.3.1           py38h06a4308_0
platformdirs              4.2.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.42             pyha770c72_0    conda-forge
psutil                    5.9.8            py38h01eb140_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycocotools               2.0.7                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.20.0                   pypi_0    pypi
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0
python                    3.8.13               h12debd9_0
python-dateutil           2.9.0.post0              pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   2.0.1           py3.8_cuda11.8_cudnn8.7.0_0
 pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.4                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     26.0.0           py38h34c975a_0    conda-forge
readline                  8.1.2                h7f8727e_1
requests                  2.28.2                   pypi_0    pypi
rich                      13.4.2                   pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                60.2.0                   pypi_0    pypi
shapely                   2.0.4                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.38.5               hc218d9a_0
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sympy                     1.12             py38h06a4308_0
tabulate                  0.9.0                    pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
terminaltables            3.1.10                   pypi_0    pypi
timm                      0.4.12                   pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tomli                     2.0.1                    pypi_0    pypi
torchaudio                2.0.2                py38_cu118    pytorch
torchhaarfeatures         0.0.2                    pypi_0    pypi
torchtriton               2.0.0                      py38    pytorch
torchvision               0.15.2               py38_cu118    pytorch
tornado                   6.4              py38h01eb140_0    conda-forge
tqdm                      4.65.2                   pypi_0    pypi
traitlets                 5.14.2             pyhd8ed1ab_0    conda-forge
typing_extensions         4.9.0            py38h06a4308_1
tzdata                    2024.1                   pypi_0    pypi
urllib3                   1.26.18                  pypi_0    pypi
wcwidth                   0.2.13             pyhd8ed1ab_0    conda-forge
wheel                     0.41.2           py38h06a4308_0
widgetsnbextension        4.0.10                   pypi_0    pypi
xz                        5.2.5                h7f8727e_1
yapf                      0.40.1                   pypi_0    pypi
zeromq                    4.3.5                h59595ed_1    conda-forge
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.12               h7f8727e_2
zstd                      1.5.2                ha4553b6_0
(MSFA) ***@***.***:


Could you send me one config file and one weight file (doesn't matter at
this stage the model) which you are sure that are updated and working and
exact python code to see detection please ?

**Comment by zcablii** [comment]
Please use the provided code and weights for model training and testing, as we verified they are working well. I am not sure why you try to run MSFA code under mmdet repo. But I think you should at lease include `import msfa` for using msfa models.

**Comment by zcablii** [comment]
Your environment looks fine. I can give you some debugging advice: prepare the dataset and change the dataset paths accordingly in the configuration, then run (for example) `python test.py ./local_configs/SARDet/other_backbones/fg_frcnn_dota_pretrain_sar_r101_wavelet.py SOME_PATH/fg_frcnn_dota_pretrain_sar_r101_wavelet/best_coco_ bbox_mAP_epoch_12.pth` to check if you get a valid result. If you encounter some general errors, you can look them up on Google. If the error is related to the mmdet framework, you can go to the "Issues" on the official mmdetection github and search for a solution. It's also possible to drill down to where the error is occurring and trace it back to the code to figure out the underlying problem (most likely some file path issue).

**Comment by paster489** [comment]
it is working. thanks a lot
