### ISSUE TITLE
quickly implements

### ISSUE THREAD

**Issue by Jordan-Liao** [zcablii/SARDet_100K#8]
Thank you for your work, may I ask when I run the command
 bash tools/dist_train.sh local_configs/SARDet/r50_IN_sup/fg_frcnn_IN_sup_sar_wavelet_r50.py 4
When I selected SAR_100k for the dataset, the checkpoint was 'ckpts/r50_sar_wavelet_epoch_100.pth' which you provided, and then why did I get an error:
![Snipaste_2024-04-07_21-47-29](https://github.com/zcablii/SARDet_100K/assets/70808352/eb40ad41-04b0-4e4b-99d0-a1d9a3a40079)

Or is there a demo that quickly implements SAR target detection? Thank you!

**Comment by zcablii** [comment]
You can safely ignore these warnings. The appearance of this warning isn't indicative of an error but rather a consequence of the Wavelet Scattering Transform's utilization of handcrafted kernels, which are dependent on the input size. Since the pretrained models were trained with images of size 224x224, fine-tuning with larger sizes such as 800x800 introduces a mismatch in the shapes of these kernels. However, it's important to note that this mismatch doesn't impact the functionality, as the weights are handcrafted and will be redefined as necessary during the process.

**Comment by ziyunxuanzzz** [comment]
Do you meet this question?


RuntimeError: GET was unable to find an engine to execute this computation
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25467) of binary: /home/xul/.conda/envs/MSFA/bin/python

**Comment by zcablii** [comment]
> Do you meet this question?
> 
> RuntimeError: GET was unable to find an engine to execute this computation ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25467) of binary: /home/xul/.conda/envs/MSFA/bin/python

It seems that your environment is not properly set up. MSFA code is totally based on [mmdetection](https://github.com/open-mmlab/mmdetection), therefore you may refer to that repo for environment installation (and do not forget to lastly run `pip install -v -e .` under MSFA folder) and find tons of solutions on the official mmdetection repo.

**Comment by ziyunxuanzzz** [comment]
> > Do you meet this question?
> > 
> > RuntimeError: GET was unable to find an engine to execute this computation ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 25467) of binary: /home/xul/.conda/envs/MSFA/bin/python
> 
> It seems that your environment is not properly set up. MSFA code is totally based on [mmdetection](https://github.com/open-mmlab/mmdetection), therefore you may refer to that repo for environment installation (and do not forget to lastly run `pip install -v -e .` under MSFA folder) and find tons of solutions on the official mmdetection repo.
> 

I just followed the way in the readme. Should I delete the conda environment and reinstall it
