### ISSUE TITLE
小白不太会运行真心请教

### ISSUE THREAD

**Issue by ziyunxuanzzz** [zcablii/SARDet_100K#9]
运行sh文件显示这个错误请问怎么解决？

dist_train.sh: 行 10: python: 未找到命令

**Comment by wokaikaixinxin** [comment]
> 运行sh文件显示这个错误请问怎么解决？
> 
> dist_train.sh: 行 10: python: 未找到命令

您好，我们的项目[ai4rs](https://github.com/wokaikaixinxin/ai4rs)展示了训练和测试指令。
